version: 2.1

orbs:
  docker: circleci/docker@1.4.0

workflows:
  build-and-deploy:
    jobs:
      - docker/publish:
          image: $HEROKU_APP_NAME/web
          deploy: false
          registry: registry.heroku.com
          tag: latest
          after_build:
            - run: |
                heroku auth:whoami
                heroku container:login
                heroku container:push -a $HEROKU_APP_NAME web
                heroku container:release -a $HEROKU_APP_NAME web

