version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2
  docker: circleci/docker@1.4.0

workflows:
  build:
    jobs:
      - docker/build:
        image: $HEROKU_APP_NAME/web
  deploy:
    jobs:
      - heroku/deploy-via-git: 
        requires:
          - build
        filters:
          branches:
            only: circleci-project-setup
