version: 2.1

orbs:
  docker: circleci/docker@1.4.0

workflows:
  build-and-deploy:
    jobs:
      - docker/publish:
          image: $HEROKU_APP_NAME
          deploy: false
          registry: registry.heroku.com
      - deploy-to-heroku:
          requires: 
            - docker/publish

jobs:
  deploy-to-heroku:
    machine: true
    steps:
      - run: |
            heroku auth:whoami
            heroku container:login
            heroku container:push -a $HEROKU_APP_NAME
            heroku container:release -a $HEROKU_APP_NAME
