orbs:
  deploy-to-heroku: betterdoc/deploy-to-heroku@4.1.0
  docker: circleci/docker@1.4.0

version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - docker/publish:
          image: $HEROKU_APP_NAME/web
          deploy: false
      - deploy-to-heroku/docker-build-release:
          app-name: $HEROKU_APP_NAME
          app-type: web
          requires: 
            - docker/publish
