orbs:
  heroku: circleci/heroku@1.2.2
  docker: circleci/docker@1.4.0

version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - docker/publish:
          image: $HEROKU_APP_NAME/web
          deploy: false
      - heroku/push-docker-image
          requires: docker/publish
